title: "ZENG Kbeznak Parmatonic"
author: "Yukun Zeng"
description: "Kbeznak Parmatonic for csce 670 homework by dr. James Caverlee"


theme: jekyll-theme-midnight
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
